logging:
  level:
    root: info
    study.example.drools.service: debug
#    org.hibernate.SQL: debug

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/anything_test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
