
import study.example.drools.domain.AirConditioner
import study.example.drools.domain.TempSensor

rule "룰 - 실내 온도가 30도 이상이면 에어컨을 켠다"
    no-loop true
    lock-on-active true
    when
      $tempSensor : TempSensor(indoorTemp >= 30)
      $airConditioner : AirConditioner(operating == false)
    then
      modify($airConditioner) { setOperating(true) }
      System.out.println($airConditioner.getAirConditionerName() + " Power On");
    end

rule "룰 - 실내 온도가 30도 미만이면 에어컨 끈다"
    no-loop true
    lock-on-active true
    when
      $tempSensor : TempSensor(indoorTemp < 30)
      $airConditioner : AirConditioner(operating == true)
    then
      modify($airConditioner) { setOperating(false) }
      System.out.println($airConditioner.getAirConditionerName() + " Power Off");
    end