
import study.example.drools.domain.Device
import study.example.drools.domain.TempSensor

rule "룰 - 실내 온도가 30도 이상이면 에어컨을 켠다"
    no-loop true
    lock-on-active true
    when
      $tempSensor : TempSensor(indoorTemp >= 30)
      $device : Device(operating == false)
    then
      modify($device) { setOperating(true) }
      System.out.println($device.getDeviceInfo() + " Power On");
    end

rule "룰 - 실내 온도가 30도 미만이면 에어컨 끈다"
    no-loop true
    lock-on-active true
    when
      $tempSensor : TempSensor(indoorTemp < 30)
      $device : Device(operating == true)
    then
      modify($device) { setOperating(false) }
      System.out.println($device.getDeviceInfo() + " Power Off");
    end