import study.example.drools.domain.TaxiRide;
import study.example.drools.domain.Fare;
import java.util.*;

global study.example.drools.domain.Fare rideFare;
dialect  "mvel"

rule "Calculate Taxi Fare - Scenario 1"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile < 10);
    then
       	rideFare.setNightSurcharge(0L);
       	rideFare.setRideFare(70L);
end

rule "Calculate Taxi Fare - Scenario 2"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile < 10);
    then
       	rideFare.setNightSurcharge(30L);
       	rideFare.setRideFare(70L);
end


rule "Calculate Taxi Fare - Scenario 3"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile >= 10 && distanceInMile < 100);
    then
       	rideFare.setNightSurcharge(0L);
       	rideFare.setRideFare(70+(2*taxiRideInstance.getDistanceInMile()));
end


rule "Calculate Taxi Fare - Scenario 4"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile >= 10 && distanceInMile < 100);
    then
       	rideFare.setNightSurcharge(30+taxiRideInstance.getDistanceInMile());
       	rideFare.setRideFare(70+(2*taxiRideInstance.getDistanceInMile()));
end


rule "Calculate Taxi Fare - Scenario 5"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile >= 100);
    then
       	rideFare.setNightSurcharge(0L);
       	rideFare.setRideFare((long) (70 + (1.5 * taxiRideInstance.getDistanceInMile())));
end

rule "Calculate Taxi Fare - Scenario 6"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile >= 100);
    then
       	rideFare.setNightSurcharge(30+taxiRideInstance.getDistanceInMile());
       	rideFare.setRideFare((long) (70 + (1.5 * taxiRideInstance.getDistanceInMile())));
end